In [ ]:
# Mount Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
%cd /content/drive/My Drive/Github/Machine Learning Course Implementations

/content/drive/My Drive/Github/Machine Learning Course Implementations


In [ ]:
ls

client_test.csv                         Submission17.csv  Submission2.csv
client_train.csv                        Submission18.csv  Submission3.csv
colabgitWorkflow.ipynb                  Submission19.csv  Submission4.csv
invoice_test.csv                        Submission20.csv  Submission5.csv
invoice_train.csv                       Submission21.csv  Submission6.csv
logs.log                                Submission22.csv  Submission7.csv
Project1:FraudDetectionChallenge.ipynb  Submission23.csv  Submission8.csv
SampleSubmission.csv                    Submission24.csv  Submission9.csv
Submission16.csv                        Submission25.csv  Submission.csv


In [ ]:
#import needed libraries 

import numpy as np
import pandas as pd
import datetime
import gc
import matplotlib.pyplot as plt
import seaborn as sns
import lightgbm as lgb
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import mean_squared_error
import warnings
warnings.filterwarnings('ignore')
np.random.seed(4590)
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.ensemble import ExtraTreesClassifier, RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier,ExtraTreeClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

from sklearn.linear_model import LinearRegression, Lasso, Ridge, LassoCV, RidgeCV, MultiTaskLassoCV, LassoLarsCV
from sklearn import datasets
from sklearn import preprocessing
from sklearn.model_selection import train_test_split, KFold, cross_val_score, GridSearchCV, LeaveOneOut
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, plot_confusion_matrix
from sklearn.preprocessing import PolynomialFeatures

from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.feature_selection import RFE

# Nouvelle section

In [ ]:
train_client=pd.read_csv('./client_train.csv')
test_client=pd.read_csv('./client_test.csv')
train_invoice=pd.read_csv('./invoice_train.csv')
test_invoice=pd.read_csv('./invoice_test.csv')
sub=pd.read_csv('./SampleSubmission.csv')

In [ ]:
train_client.head()

disrict          client_id  client_catg  region creation_date  target
0       60     train_Client_0           11     101    31/12/1994     0.0
1       69     train_Client_1           11     107    29/05/2002     0.0
2       62    train_Client_10           11     301    13/03/1986     0.0
3       69   train_Client_100           11     105    11/07/1996     0.0
4       62  train_Client_1000           11     303    14/10/2014     0.0

In [ ]:
train_invoice.head(10)

client_id invoice_date  ...  months_number  counter_type
0  train_Client_0   2014-03-24  ...              4          ELEC
1  train_Client_0   2013-03-29  ...              4          ELEC
2  train_Client_0   2015-03-23  ...              4          ELEC
3  train_Client_0   2015-07-13  ...              4          ELEC
4  train_Client_0   2016-11-17  ...             12          ELEC
5  train_Client_0   2017-07-17  ...              8          ELEC
6  train_Client_0   2018-12-07  ...             12          ELEC
7  train_Client_0   2019-03-19  ...              8          ELEC
8  train_Client_0   2011-07-22  ...              4          ELEC
9  train_Client_0   2011-11-22  ...              4          ELEC

[10 rows x 16 columns]

In [ ]:
d={"ELEC":0,"GAZ":1}
train_invoice['counter_type']=train_invoice['counter_type'].map(d)

In [ ]:
train_client['client_catg'] = train_client['client_catg'].astype('object')
train_client['disrict'] = train_client['disrict'].astype('object')

test_client['client_catg'] = test_client['client_catg'].astype('object')
test_client['disrict'] = test_client['disrict'].astype('object')

In [ ]:
train_invoice['counter_type'].value_counts()

0    3079406
1    1397343
Name: counter_type, dtype: int64

In [ ]:
for df in [train_invoice,test_invoice]:
    df['invoice_date'] = pd.to_datetime(df['invoice_date'])
    df['year'] = df['invoice_date'].dt.year
    df['month'] = df['invoice_date'].dt.month


In [ ]:
aggs = {}
aggs['consommation_level_1'] = ['sum','max','min','mean','std']
aggs['consommation_level_2'] = ['sum','max','min','mean','std']
aggs['consommation_level_3'] = ['sum','max','min','mean','std']
aggs['consommation_level_4'] = ['sum','max','min','mean','std']

aggs['month'] = ['mean', 'max', 'min', 'std']
aggs['year'] = ['nunique','max','min','mean']

aggs['months_number'] = ['max','min','mean','sum']
aggs['reading_remarque'] = ['max','min','mean','std','sum']
aggs['counter_coefficient'] = ['max', 'min','mean']
aggs['counter_number'] = ['nunique']
aggs['counter_type'] = ['nunique','mean','sum']
aggs['counter_statue'] = ['nunique']
aggs['tarif_type'] = ['nunique','max','min']
aggs['counter_code'] = ['nunique','max','mean','min']


aggs['old_index'] = ['nunique','mean','std']
aggs['old_index'] = ['nunique','mean','std']





In [ ]:
    agg_trans = train_invoice.groupby(['client_id']).agg(aggs)
    agg_trans.columns = ['_'.join(col).strip() for col in agg_trans.columns.values]
    agg_trans.reset_index(inplace=True)

    df = (train_invoice.groupby('client_id')
          .size()
          .reset_index(name='{}transactions_count'.format('1')))

    agg_trans = pd.merge(df, agg_trans, on='client_id', how='left')

In [ ]:
agg_trans.head()

client_id  1transactions_count  ...  old_index_mean  old_index_std
0     train_Client_0                   35  ...     9444.542857    4527.744415
1     train_Client_1                   37  ...    14330.756757    6124.126094
2    train_Client_10                   18  ...    32873.000000    5317.180865
3   train_Client_100                   20  ...       94.150000       4.120232
4  train_Client_1000                   14  ...     6900.428571    4732.111217

[5 rows x 57 columns]

In [ ]:
train = pd.merge(train_client,agg_trans, on='client_id', how='left')

In [ ]:
test_client.head()

disrict         client_id client_catg  region creation_date
0      62     test_Client_0          11     307    28/05/2002
1      69     test_Client_1          11     103    06/08/2009
2      62    test_Client_10          11     310    07/04/2004
3      60   test_Client_100          11     101    08/10/1992
4      62  test_Client_1000          11     301    21/07/1977

In [ ]:
test_invoice.head()

client_id invoice_date  tarif_type  ...  counter_type  year  month
0  test_Client_0   2018-03-16          11  ...          ELEC  2018      3
1  test_Client_0   2014-03-21          11  ...          ELEC  2014      3
2  test_Client_0   2014-07-17          11  ...          ELEC  2014      7
3  test_Client_0   2015-07-13          11  ...          ELEC  2015      7
4  test_Client_0   2016-07-19          11  ...          ELEC  2016      7

[5 rows x 18 columns]

In [ ]:
d={"ELEC":0,"GAZ":1}
test_invoice['counter_type']=test_invoice['counter_type'].map(d)

In [ ]:
    agg_trans = test_invoice.groupby(['client_id']).agg(aggs)
    agg_trans.columns = ['_'.join(col).strip() for col in agg_trans.columns.values]
    agg_trans.reset_index(inplace=True)

    df = (test_invoice.groupby('client_id')
          .size()
          .reset_index(name='{}transactions_count'.format('1')))

    agg_trans = pd.merge(df, agg_trans, on='client_id', how='left')

In [ ]:
test = pd.merge(test_client,agg_trans, on='client_id', how='left')

In [ ]:
train.head(50)


disrict            client_id  ... old_index_mean  old_index_std
0       60       train_Client_0  ...    9444.542857    4527.744415
1       69       train_Client_1  ...   14330.756757    6124.126094
2       62      train_Client_10  ...   32873.000000    5317.180865
3       69     train_Client_100  ...      94.150000       4.120232
4       62    train_Client_1000  ...    6900.428571    4732.111217
5       69   train_Client_10000  ...   13789.625000   10536.192177
6       62  train_Client_100000  ...   19788.750000   16818.314522
7       60  train_Client_100001  ...    6583.141026    6652.875339
8       62  train_Client_100002  ...       3.500000       4.949747
9       60  train_Client_100003  ...    9342.200000   12838.345812
10      63  train_Client_100004  ...     874.538462    1040.995566
11      62  train_Client_100005  ...   23723.881579   19948.905309
12      69  train_Client_100006  ...   19664.891892   13073.181834
13      60  train_Client_100007  ...    3568.730769    1443.202122
14      69  train_Client_100008  ...    2763.000000       0.000000
15      63  train_Client_100009  ...    2810.527778     599.461639
16      63   train_Client_10001  ...   15483.027778    9187.924624
17      69  train_Client_100010  ...    5830.666667    5659.994511
18      63  train_Client_100011  ...    6036.076923    9763.729492
19      60  train_Client_100012  ...   22197.600000   15524.074892
20      62  train_Client_100013  ...   11537.951923   12116.455193
21      60  train_Client_100014  ...    6480.000000     314.399427
22      63  train_Client_100015  ...    3324.700000    2690.557487
23      60  train_Client_100016  ...    5415.708861    3659.012919
24      69  train_Client_100017  ...    8747.500000   10437.983256
25      69  train_Client_100018  ...    4865.000000            NaN
26      69  train_Client_100019  ...   42260.393939   20627.288780
27      63   train_Client_10002  ...   18993.837838   17050.673064
28      60  train_Client_100020  ...   16263.513514   10185.894276
29      69  train_Client_100021  ...   35491.222222   20739.264083
30      60  train_Client_100022  ...   22115.537500   19629.745435
31      63  train_Client_100023  ...    6918.750000     899.802710
32      60  train_Client_100024  ...   26752.662338   33772.128494
33      63  train_Client_100025  ...    4728.407407    4903.994369
34      63  train_Client_100026  ...      22.625000      40.238352
35      63  train_Client_100027  ...   11968.611111    5533.880572
36      60  train_Client_100028  ...   13685.815789   13742.206145
37      62  train_Client_100029  ...   23874.333333    1412.991389
38      60   train_Client_10003  ...   16826.142857    2098.417374
39      60  train_Client_100030  ...   49235.000000            NaN
40      62  train_Client_100031  ...   26925.592593    3386.767397
41      63  train_Client_100032  ...    3044.722222    2063.602954
42      63  train_Client_100033  ...       0.000000            NaN
43      60  train_Client_100034  ...    8947.285714    9182.922228
44      69  train_Client_100035  ...   76640.916667    7598.733357
45      62  train_Client_100036  ...    6899.815789    6729.857574
46      62  train_Client_100037  ...   10871.652174    6728.174220
47      63  train_Client_100038  ...    8612.709677    4438.526063
48      60  train_Client_100039  ...    1744.333333       2.081666
49      60   train_Client_10004  ...    6976.000000     395.979797

[50 rows x 62 columns]

In [ ]:
test.head()

disrict         client_id  ... old_index_mean  old_index_std
0      62     test_Client_0  ...   11389.837838    5401.043096
1      69     test_Client_1  ...   29380.772727   17638.422718
2      62    test_Client_10  ...   11774.054054   10987.377541
3      60   test_Client_100  ...   13623.725000   13242.361986
4      62  test_Client_1000  ...   13927.471698   14371.199312

[5 rows x 61 columns]

In [ ]:
train.shape,test.shape

((135493, 62), (58069, 61))

In [ ]:
for df in [train,test]:
    df['creation_date'] = pd.to_datetime(df['creation_date'])
    df['year'] = df['creation_date'].dt.year
    df['month'] = df['creation_date'].dt.month
    df['month_diff'] = ((datetime.datetime.today() - df['creation_date']).dt.days)//30

In [ ]:
col_to_drop = ['client_id', 'creation_date','old_index_std','reading_remarque_std','month_std','consommation_level_1_std', 'consommation_level_2_std', 'consommation_level_3_std','consommation_level_4_std']
for col in col_to_drop:
    if col in train.columns:
        train.drop([col], axis=1, inplace=True)
    if col in test.columns:
        test.drop([col], axis=1, inplace=True)

In [ ]:
test.head()

disrict client_catg  region  ...  year  month  month_diff
0      62          11     307  ...  2002      5         238
1      69          11     103  ...  2009      6         152
2      62          11     310  ...  2004      7         212
3      60          11     101  ...  1992      8         357
4      62          11     301  ...  1977      7         540

[5 rows x 55 columns]

In [ ]:
from sklearn import preprocessing
for f in test.columns:
    if train[f].dtype=='object' or test[f].dtype=='object': 
        lbl = preprocessing.LabelEncoder()
        lbl.fit(list(train[f].values) + list(test[f].values))
        train[f] = lbl.transform(list(train[f].values))
        test[f] = lbl.transform(list(test[f].values))  

In [ ]:
test.head()

disrict  client_catg  region  ...  year  month  month_diff
0        1            0     307  ...  2002      5         238
1        3            0     103  ...  2009      6         152
2        1            0     310  ...  2004      7         212
3        0            0     101  ...  1992      8         357
4        1            0     301  ...  1977      7         540

[5 rows x 55 columns]

In [ ]:
all_data_na = train.isnull().sum() 
all_data_na = all_data_na.drop(all_data_na[all_data_na == 0].index).sort_values(ascending=False)[:30]
missing_data = pd.DataFrame({'Missing ' :all_data_na})
missing_data.head(20)

Empty DataFrame
Columns: [Missing ]
Index: []

In [ ]:
train.head()

disrict  client_catg  region  ...  year  month  month_diff
0        0            0     101  ...  1994     12         328
1        3            0     107  ...  2002      5         238
2        1            0     301  ...  1986      3         435
3        3            0     105  ...  1996     11         305
4        1            0     303  ...  2014     10          87

[5 rows x 56 columns]

### Models

In [ ]:
target=train['target']
train.drop('target',axis=1,inplace=True)

In [ ]:
test.head()

disrict  client_catg  region  ...  year  month  month_diff
0        1            0     307  ...  2002      5         238
1        3            0     103  ...  2009      6         152
2        1            0     310  ...  2004      7         212
3        0            0     101  ...  1992      8         357
4        1            0     301  ...  1977      7         540

[5 rows x 55 columns]

In [ ]:
import lightgbm
from lightgbm import LGBMRegressor
from lightgbm import LGBMClassifier
model = LGBMClassifier(boosting_type='gbdt',num_iteration=500, silent=True)

#Fit to training data
%time model.fit(train,target)

CPU times: user 42.2 s, sys: 237 ms, total: 42.4 s
Wall time: 29.5 s


LGBMClassifier(num_iteration=500)

In [ ]:
import xgboost as xgb
from datetime import datetime
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import StratifiedKFold
clf = xgb.XGBClassifier(
    n_estimators=500,
    max_depth=9,
    learning_rate=0.05,
    subsample=0.9,
    colsample_bytree=0.9,
    random_state=2019,
)
%time clf.fit(train, target)

CPU times: user 6min 58s, sys: 816 ms, total: 6min 59s
Wall time: 7min 3s


XGBClassifier(colsample_bytree=0.9, learning_rate=0.05, max_depth=9,
              n_estimators=500, random_state=2019, subsample=0.9)

In [ ]:
pred=clf.predict_proba(test)
pred

array([[0.9833939 , 0.01660611],
       [0.919286  , 0.08071401],
       [0.9838366 , 0.01616339],
       ...,
       [0.30841374, 0.69158626],
       [0.9981327 , 0.00186728],
       [0.9500115 , 0.04998852]], dtype=float32)

In [ ]:
lgbm_pred=model.predict_proba(test)
lgbm_pred.shape

(58069, 2)

In [ ]:
lgbm_pred[0]

array([0.98503937, 0.01496063])

### ExtraTree clf

In [ ]:
from sklearn.ensemble import ExtraTreesClassifier
model = ExtraTreeClassifier( n_jobs=4, min_samples_split=25,
                            min_samples_leaf=35, max_features=150)
                            
gsc = GridSearchCV(
    estimator=model,
    param_grid={
        #'n_estimators': range(50,126,25),
        'max_features': range(50,401,50),
        'criterion': ['gini','entropy'],
    },
    scoring='accuracy',
    cv=5
)

grid_result = gsc.fit(train, target)

print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

Best: 0.944779 using {'criterion': 'gini', 'max_features': 50}


In [ ]:
extratree_clf = ExtraTreeClassifier( criterion= 'gini', max_features=50)
%time extratree_clf.fit(train, target)

CPU times: user 1.42 s, sys: 8.98 ms, total: 1.43 s
Wall time: 1.48 s


ExtraTreeClassifier(max_features=50)

In [ ]:
extratree_pred=extratree_clf.predict_proba(test)
extratree_pred.shape

(58069, 2)

### RF

In [ ]:
rf_clf = RandomForestClassifier(criterion= 'gini', max_features=30)
%time rf_clf.fit(train, target)

CPU times: user 3min 22s, sys: 265 ms, total: 3min 22s
Wall time: 3min 24s


RandomForestClassifier(max_features=30)

In [ ]:
rf_pred=rf_clf.predict_proba(test)
rf_pred.shape

(58069, 2)

In [ ]:
rf_pred

array([[1.  , 0.  ],
       [0.81, 0.19],
       [0.99, 0.01],
       ...,
       [0.46, 0.54],
       [1.  , 0.  ],
       [0.98, 0.02]])

### KNN

In [ ]:
knn_clf = KNeighborsClassifier()
%time knn_clf.fit(train, target)

CPU times: user 49.1 ms, sys: 6.03 ms, total: 55.2 ms
Wall time: 67.7 ms


KNeighborsClassifier()

In [ ]:
knn_pred=knn_clf.predict_proba(test)
knn_pred.shape

KeyboardInterrupt: ignored

In [ ]:
knn_pred

array([[1. , 0. ],
       [0.8, 0.2],
       [1. , 0. ],
       ...,
       [0.6, 0.4],
       [1. , 0. ],
       [0.8, 0.2]])

### DecisionTreeClassifier

In [ ]:
dtree_clf = DecisionTreeClassifier()
%time dtree_clf.fit(train, target)

CPU times: user 4.62 s, sys: 21.8 ms, total: 4.64 s
Wall time: 4.63 s


DecisionTreeClassifier()

In [ ]:
dtree_pred=dtree_clf.predict_proba(test)
dtree_pred.shape

(58069, 2)

In [ ]:
dtree_pred

NameError: ignored

### SVC

In [ ]:
from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
svc_clf = make_pipeline(StandardScaler(), SVC(gamma='auto')) #Faster computation
%time svc_clf.fit(train, target)

In [ ]:
svc_pred=svc_clf.predict_proba(test)
svc_pred.shape

In [ ]:
svc_pred

### AdaBoostClassifier

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
ada_clf = AdaBoostClassifier() #Faster computation
%time ada_clf.fit(train, target)

CPU times: user 20.4 s, sys: 105 ms, total: 20.5 s
Wall time: 20.5 s


AdaBoostClassifier()

In [ ]:
ada_pred=ada_clf.predict_proba(test)
ada_pred.shape

(58069, 2)

In [ ]:
ada_pred

array([[0.51849911, 0.48150089],
       [0.51210667, 0.48789333],
       [0.51369718, 0.48630282],
       ...,
       [0.50871273, 0.49128727],
       [0.52730938, 0.47269062],
       [0.5098782 , 0.4901218 ]])

### Result

In [ ]:
preds=pred[:,1]*0.4+0.3*lgbm_pred[:,1]+ 0.1*rf_pred[:,1]+ 0.2*ada_pred[:,1]

In [ ]:
preds = pd.DataFrame(preds)

In [ ]:
preds.head()

0
0  0.107431
1  0.192499
2  0.108930
3  0.097026
4  0.172219

### Stacking Models - Blending

In [ ]:
!pip install mlxtend

In [ ]:
!pip install mlrose

In [ ]:
import six
import sys
sys.modules['sklearn.externals.six'] = six
import mlrose

In [ ]:
from mlxtend.classifier import StackingCVClassifier

stack_gen = StackingCVClassifier(classifiers=(ada_clf, rf_clf, model),
                                 use_probas=True,
                                 meta_classifier=clf)
%time stack_gen.fit(np.array(train), np.array(target))

CPU times: user 10min 16s, sys: 2.23 s, total: 10min 18s
Wall time: 10min 17s


StackingCVClassifier(classifiers=(AdaBoostClassifier(),
                                  RandomForestClassifier(max_features=30),
                                  LGBMClassifier(num_iteration=500)),
                     meta_classifier=StackingClassifier(estimators=[('rf',
                                                                     RandomForestClassifier(n_estimators=10,
                                                                                            random_state=42)),
                                                                    ('svr',
                                                                     Pipeline(steps=[('standardscaler',
                                                                                      StandardScaler()),
                                                                                     ('linearsvc',
                                                                                      LinearSVC(random_state=42))]))],
 

In [ ]:
stack_gen_pred=stack_gen.predict_proba(test)
stack_gen_pred.shape

(58069, 2)

In [ ]:
stack_gen_pred

array([[0.97425648, 0.02574352],
       [0.92276852, 0.07723148],
       [0.97053287, 0.02946713],
       ...,
       [0.23955546, 0.76044454],
       [0.97790778, 0.02209222],
       [0.96138769, 0.03861231]])

In [ ]:
preds= stack_gen_pred[:,1]
preds = pd.DataFrame(preds)
preds

0
0      0.025744
1      0.077231
2      0.029467
3      0.021470
4      0.058709
...         ...
58064  0.022804
58065  0.029269
58066  0.760445
58067  0.022092
58068  0.038612

[58069 rows x 1 columns]

In [ ]:
def blend(X):
    return ((0.1 * rf_clf.predict_proba(X)) + \
            (0.2 * model.predict_proba(X)) + \
            (0.2 * clf.predict_proba(X)) + \
            (0.15 * ada_clf.predict_proba(X)) + \
            (0.35 * stack_gen.predict_proba(np.array(X))))

In [ ]:
preds=pred[:,1]*0.2+0.2*lgbm_pred[:,1]+ 0.1*rf_pred[:,1]+ 0.15*ada_pred[:,1]+ 0.35*stack_gen_pred[:,1]
preds = pd.DataFrame(preds)
preds

0
0      0.087549
1      0.164448
2      0.090294
3      0.079995
4      0.144206
...         ...
58064  0.080634
58065  0.095906
58066  0.639512
58067  0.079315
58068  0.112819

[58069 rows x 1 columns]

In [ ]:
submission = pd.DataFrame({
        "client_id": sub["client_id"],
        "target": preds[0]
    })
submission.to_csv('Submission34.csv', index=False)



In [ ]:
#@title Default title text
submission.head(58071)

client_id    target
0         test_Client_0  0.087549
1         test_Client_1  0.164448
2        test_Client_10  0.090294
3       test_Client_100  0.079995
4      test_Client_1000  0.144206
...                 ...       ...
58064  test_Client_9995  0.080634
58065  test_Client_9996  0.095906
58066  test_Client_9997  0.639512
58067  test_Client_9998  0.079315
58068  test_Client_9999  0.112819

[58069 rows x 2 columns]

In [ ]:
# pred[:,1]*0.3+0.7*lgbm_pred[:,1]
# Best: pred[:,1]*0.4+0.5*lgbm_pred[:,1]+ 0.1*rf_pred[:,1]
# pred[:,1]*0.4+0.4*lgbm_pred[:,1]+ 0.1*rf_pred[:,1]+0.1*knn_pred[:,1] => Bad sub22
# preds=pred[:,1]*0.35+0.35*lgbm_pred[:,1]+ 0.1*rf_pred[:,1]+ 0.2*ada_pred[:,1] => Best (4th)